### ISSUE TITLE
Auto-Fill banking details into name box

### ISSUE THREAD

**Issue by rekoJgnikoJ** [deltapi/abc-feedback#27]
When I went to fill in my name, for some reason chrome (latest update as of posting) initially suggests I fill in my banking details, versus any other stashed cookies. When I begin to type in a username that I have used before, it does luckily suggest that. 
I do have auto-fill enabled in chrome, just surprised it thought it would pop up here. Not sure if this is a Chrome issue or a website issue, thought I'd post in case it is the latter.

![image](https://user-images.githubusercontent.com/94469444/142016965-84c9a881-b29e-4691-90bf-11f938fdc718.png)

Interesting to say the least....

**Comment by deltapi** [comment]
Hey, neither did we request any other information than a nickname nor will we ever do so in the future. We value your privacy and this project is not about any other data than abc-triples. Please report this to the chrome devs, as your browser certainly should not suggest auto-filling your bank-data as a first choice in autofill. I will close the issue, because it is not related to our software. Feel free to reopen in case you have new information.

**Comment by rekoJgnikoJ** [comment]
No worries, it's obviously nothing malicious on your end. I'll pass it onto the chrome people. I'll give an update here if I hear anything!

**Comment by rekoJgnikoJ** [comment]
No worries, it's obviously nothing malicious on your end. I'll pass it onto the chrome people, and I'll give an update here if I hear anything!
